language: java

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - sudo R CMD javareconf
  - ./travis-tool.sh r_binary_install Rcpp
  - ./travis-tool.sh r_binary_install rgl
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install RJSONIO
  - ./travis-tool.sh r_binary_install RSQLite
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package rstudio/shiny
  - ./travis-tool.sh github_package mul118/shinyMCE
  - ./travis-tool.sh github_package mul118/shinyGridster
  - ./travis-tool.sh github_package trestletech/shinyAce
  - ./travis-tool.sh github_package iheartradio/ShinyBuilder
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

branches:
  except:
  - /-expt$/
